### ISSUE TITLE
format does not match influxdb protocol

### ISSUE THREAD

**Issue by schaefer01** [awelzel/influxpy#1]
hi,
  have you tested using a udp on a remote server running influxdb instead of localhost?

  I'm using your example and seeing error messages, an earlier part of the field is compared against the timestamp
  Time is not outside range, but the field interpreted as a timestamp is.

https://docs.influxdata.com/influxdb/v1.4/write_protocols/line_protocol_tutorial/#syntax

my server influx error message:

info	Failed to parse points	{"log_id": "0hLERoQG000", "service": "udp", "error": "unable to parse 'udp,app=snakeoil,datacenter=us-west,host=C02D81GJMD6W.tld,level=7,level_name=DEBUG,logger=test_logger message=\"It is warm.\",temperature=26.3 1682098994109021952': time outside range -9223372036854775806 - 9223372036854775806"}
2023-04-21T17:43:14.210312Z	info	Failed to parse points	{"log_id": "0hLERoQG000", "service": "udp", "error": "unable to parse 'mylogs,app=snakeoil,datacenter=us-west,host=C02D81GJMD6W.tld,level=7,level_name=DEBUG,logger=test_logger message=\"It is warm.\",temperature=26.3 1682098994109021952': time outside range -9223372036854775806 - 9223372036854775806"}

**Comment by schaefer01** [comment]
hi,
  I solved my problem

   the timestamp precision needs to match the influxdb.conf file and this is not documented anywhere

   this does not affect the library, so I'm closing the issue

**Comment by awelzel** [comment]
Thank you @schaefer01 for investigating further.

**Comment by schaefer01** [comment]
You are welcome. I spent two days instrumenting and adusting your code to discover influx error messages are terrible and shouldn't be trusted, only to finally realize the first error message was telling the truth but not providing context, it was telling me a half-truth. Once I had proven to myself your protocol was correct, the solution was to figure out the right question to ask google.
https://community.influxdata.com/t/timestamp-rejected-for-being-out-of-range-despite-falling-within-range/3899

**Comment by schaefer01** [comment]
One more note, the name of the database in influx is the name under the [[udp]] header in the influxdb.conf file at the tag database=
